export const TABLE_COLUMNS = [
  {
    columnDef: "idx",
    header: "Id",
    cell: (element: any) => `${element.idx}`,
    controlType: "Label",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "Id",
    openPop: false,
  },
  {
    columnDef: "name",
    header: "Name",
    cell: (element: any) => `${element.name}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Name",
    openPop: false,
  },
  {
    columnDef: "template",
    header: "Template",
    cell: (element: any) => `${element.template}`,
    controlType: "text",
    isReadOnly: true,
    placeholder: "Template",
    isControlRequired: true,
    isValidationPattern: null,
    openPop: true,
  },
  {
    columnDef: "maxLength",
    header: "Max Length",
    cell: (element: any) => `${element.maxLength}`,
    controlType: "Label",
    isReadOnly: true,
    placeholder: "Max Length",
    isControlRequired: true,
    isValidationPattern: null,
    openPop: false,
  },

  {
    columnDef: "action",
    header: "",
    cell: (element: any) => `${element.Action}`,
  },
];
