export const TABLE_COLUMNS = [
  {
    columnDef: "select",
    header: "",
    cell: (element: any) => `${element.select}`,
  },
  {
    columnDef: "id",
    header: "ID",
    cell: (element: any) => `${element.id}`,
    controlType: "Label",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "ID",
    isNotEditableCell: false,
  },
  {
    columnDef: "name",
    header: "Name",
    cell: (element: any) => `${element.name}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Name",
    isNotEditableCell: false,
  },
  {
    columnDef: "depositor",
    header: "Depositor",
    cell: (element: any) => `${element.depositor}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Depositor",
    isNotEditableCell: false,
  },
  {
    columnDef: "warehouse",
    header: "Warehouse",
    cell: (element: any) => `${element.warehouse}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Warehouse",
    isNotEditableCell: false,
  },
  {
    columnDef: "base_uom",
    header: "Base_Uom",
    cell: (element: any) => `${element.base_uom}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Base_uom",
    isNotEditableCell: false,
  },
  {
    columnDef: "description",
    header: "Description",
    cell: (element: any) => `${element.description}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Description",
    isNotEditableCell: false,
  },
  {
    columnDef: "upc",
    header: "Upc",
    cell: (element: any) => `${element.upc}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Upc",
    isNotEditableCell: false,
  },
  {
    columnDef: "action",
    header: "",
    cell: (element: any) => `${element.Action}`,
  },
];
