export const TABLE_COLUMNS = [
  {
    columnDef: "select",
    header: "",
    cell: (element: any) => `${element.select}`,
  },
  {
    columnDef: "idx",
    header: "User ID",
    cell: (element: any) => `${element.idx}`,
    controlType: "Label",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "UserID",
  },
  {
    columnDef: "name",
    header: "Name",
    cell: (element: any) => `${element.name}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Name",
  },
  {
    columnDef: "allowed_depositors",
    header: "Depositor",
    cell: (element: any) => `${element.allowed_depositors}`,
    controlType: "multi-select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Depositor",
    optionsKey: "settings_depositors",
  },
  {
    columnDef: "email",
    header: "Email",
    cell: (element: any) => `${element.email}`,
    controlType: "text",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "Email",
  },
  {
    columnDef: "role_id",
    header: "Role",
    cell: (element: any) => `${element.role_id}`,
    controlType: "select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Role",
    optionsKey: "dim_user_roles",
  },

  {
    columnDef: "action",
    header: "",
    cell: (element: any) => `${element.Action}`,
  },
];
