export const TABLE_COLUMNS = [
  {
    columnDef: "select",
    header: "",
    cell: (element: any) => `${element.select}`,
  },
  {
    columnDef: "idx",
    header: "Driver ID",
    cell: (element: any) => `${element.idx}`,
    controlType: "Label",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "DriverID",
  },
  {
    columnDef: "name",
    header: "Name",
    cell: (element: any) => `${element.name}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Name",
  },
  {
    columnDef: "last_name",
    header: "Last Name",
    cell: (element: any) => `${element.last_name}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "LastName",
  },
  {
    columnDef: "phone",
    header: "Phone",
    cell: (element: any) => `${element.phone}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: "[0-9]{10}",
    placeholder: "Phone",
  },
  {
    columnDef: "email",
    header: "Email",
    cell: (element: any) => `${element.email}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Email",
  },
  {
    columnDef: "tms_type_header",
    header: "TMS Type header",
    cell: (element: any) => `${element.tms_type_header}`,
    controlType: "select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "TMS Type header",
    optionsKey: "dim_tms_types",
  },
  {
    columnDef: "status_mapping",
    header: "Status mapping",
    cell: (element: any) => `${element.status_mapping}`,
    controlType: "select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Status mapping",
    optionsKey: "status_mapping",
  },
  {
    columnDef: "description",
    header: "Description",
    cell: (element: any) => `${element.description}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Description",
  },
  {
    columnDef: "area_id",
    header: "Area Id",
    cell: (element: any) => `${element.area_id}`,
    controlType: "select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Area Id",
    optionsKey: "area_id",
  },
  {
    columnDef: "stops",
    header: "Stops",
    cell: (element: any) => `${element.stops}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Stops",
  },
  {
    columnDef: "startlocation",
    header: "Startlocation",
    cell: (element: any) => `${element.startlocation}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Start location",
  },

  {
    columnDef: "action",
    header: "",
    cell: (element: any) => `${element.Action}`,
  },
];
