export const TABLE_COLUMNS = [
  {
    columnDef: "select",
    header: "",
    cell: (element: any) => `${element.select}`,
  },
  {
    columnDef: "idx",
    header: "Depositor Id",
    cell: (element: any) => `${element.idx}`,
    controlType: "Label",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "Depositor Id",
  },
  {
    columnDef: "name",
    header: "Name",
    cell: (element: any) => `${element.name}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Name",
  },
  {
    columnDef: "client_code",
    header: "eGold Code",
    cell: (element: any) => `${element.client_code}`,
    controlType: "Label",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "eGold Code",
  },
  {
    columnDef: "default_sd_courier_id",
    header: "Default SD",
    cell: (element: any) => `${element.default_sd_courier_id}`,
    controlType: "select",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "Default SD",
    optionsKey: "dim_couriers",
  },
  {
    columnDef: "default_nd_courier_id",
    header: "Default ND",
    cell: (element: any) => `${element.default_nd_courier_id}`,
    controlType: "select",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "Default ND",
    optionsKey: "dim_couriers",
  },
  {
    columnDef: "default_locker_courier_id",
    header: "Default LOCKER",
    cell: (element: any) => `${element.default_locker_courier_id}`,
    controlType: "select",
    isControlRequired: false,
    isValidationPattern: null,
    placeholder: "Default LOCKER",
    optionsKey: "dim_couriers",
  },
  {
    columnDef: "override_global_couriers",
    header: "Override global couriers",
    cell: (element: any) => `${element.override_global_couriers}`,
    controlType: "select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Override global couriers",
    optionsKey: "dim_override_global_couriers",
  },
  {
    columnDef: "contact_email",
    header: "Email",
    cell: (element: any) => `${element.contact_email}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Email",
  },
  {
    columnDef: "contact_phone",
    header: "Contact phone(s)",
    cell: (element: any) => `${element.contact_phone}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Contact phone(s)",
  },
  {
    columnDef: "shop_webhook_url",
    header: "Shop url",
    cell: (element: any) => `${element.shop_webhook_url}`,
    controlType: "text",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Shop url",
  },

  {
    columnDef: "shop_plugin_id",
    header: "Shop Plugin",
    cell: (element: any) => `${element.shop_plugin_id}`,
    controlType: "select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Shop plugin-typen",
    optionsKey: "dim_shop_plugin_types",
  },
  {
    columnDef: "locker_suppliers",
    header: "Locker suppliers",
    cell: (element: any) => `${element.locker_suppliers}`,
    controlType: "multi-select",
    isControlRequired: true,
    isValidationPattern: null,
    placeholder: "Locker Suppliers",
    optionsKey: "dim_locker_suppliers",
  },
  {
    columnDef: "action",
    header: "",
    cell: (element: any) => `${element.Action}`,
  },
];
